---
- hosts: WEB
  sudo: yes

  tasks:
  - name: Create group named deploy
    group: name=deploy
  - name: Add user to a group
    user: name=deploy-user group=group append=yes shell=/bin/bash
  - name: Ensure that Apache is installed
    yum: name=httpd state=present
  - name: Start Apache Services
    service: name=httpd enabled=yes state=started
  - lineinfile:
      path: /opt/index.html
      create: yes
      line: New Line should be added
  - name: Ensure that server is rebooted
    reboot:
