---
- name: This sets up an httpd webserver
  hosts: localhost
  tasks:
  - name: example copying file with owner and permissions
    copy:
      src: /opt/test.sh
      dest: /tmp/test.sh
      mode: 777
- name: Include a play after another play
  include: playbook22.yaml
