---
# tasks file for ansibleProject
  - name: Install WebServer
    yum: name=httpd state=present
  - script: files/execshell.sh
    register: find_output
  - name: install Modules
    yum: pkg={{item}} state=installed
    with_items:
     - git
     - ntp
     - vim
  - name: Copy Site Files
    template: src=index.j2 dest=/var/www/html/index.html
  - name: Copy Httpd
    template: src=httpd.j2 dest=/etc/httpd/conf/httpd.conf
    notify:
      - restart_httpd
#  - debug:
#     var: find_output
